config/routes.rb
Rails.application.routes.draw do
  resources :complications
  resources :operation_records
  resources :doctors
  resources :patients

  root 'operation_records#index'

end

app/models/complication.rb
# == Schema Information
#
# Table name: complications
#
#  id                  :integer          not null, primary key
#  operation_record_id :integer
#  description         :string
#  wound_infection     :boolean
#  death               :boolean
#  preventable         :boolean
#  death_preventable   :boolean
#  anesthesia_related  :boolean
#  error_type          :string           is an Array
#  error_grade         :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
# Indexes
#
#  index_complications_on_operation_record_id  (operation_record_id)
#
# Foreign Keys
#
#  fk_rails_bf03b390c7  (operation_record_id => operation_records.id)
#

class Complication < ActiveRecord::Base
  
  ErrorTypes = ['Technical', 'Judgement', 'Systems', 'Knowledge Deficit', 'Other (explain in description)']
  ErrorGrades = %w(I II IIIa IIIb IVa IVb V)
  ErrorGradesWithSuffix = ErrorGrades.map { |g| [g, "#{g}-d"] }.flatten
  
  belongs_to :operation_record
end

app/controllers/complications_controller.rb
class ComplicationsController < ApplicationController
  before_action :set_complication, only: [:show, :edit, :update, :destroy]

  # GET /complications
  # GET /complications.json
  def index
    @complications = Complication.all
  end

  # GET /complications/1
  # GET /complications/1.json
  def show
  end

  # GET /complications/new
  def new
    @complication = Complication.new
  end

  # GET /complications/1/edit
  def edit
  end

  # POST /complications
  # POST /complications.json
  def create
    @complication = Complication.new(complication_params)

    respond_to do |format|
      if @complication.save
        format.html { redirect_to @complication, notice: 'Complication was successfully created.' }
        format.json { render :show, status: :created, location: @complication }
      else
        format.html { render :new }
        format.json { render json: @complication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complications/1
  # PATCH/PUT /complications/1.json
  def update
    respond_to do |format|
      if @complication.update(complication_params)
        format.html { redirect_to @complication, notice: 'Complication was successfully updated.' }
        format.json { render :show, status: :ok, location: @complication }
      else
        format.html { render :edit }
        format.json { render json: @complication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complications/1
  # DELETE /complications/1.json
  def destroy
    @complication.destroy
    respond_to do |format|
      format.html { redirect_to complications_url, notice: 'Complication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complication
      @complication = Complication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complication_params
      params.require(:complication).permit(:operation_record_id, :description, :wound_infection, :death, :preventable, :death_preventable, :anesthesia_related, :error_type, :error_grade)
    end
end

app/helpers/complications_helper.rb
module ComplicationsHelper
end

app/views/complications/_form.html.haml
= form_for @complication do |f|
  - if @complication.errors.any?
    #error_explanation
      %h2= "#{pluralize(@complication.errors.count, "error")} prohibited this complication from being saved:"
      %ul
        - @complication.errors.full_messages.each do |msg|
          %li= msg

  .row.column
    = f.label :operation_record_id
    = f.select :operation_record_id, OperationRecord.all.collect { |op_rec| [op_rec.short_desc, op_rec.id] },
                                     { prompt: 'Select operation record'}, required: true
  .row.column
    %fieldset.fieldset
      %legend Complication issues
      .row.column
        = f.check_box :preventable
        = f.label :preventable
        = f.check_box :death
        = f.label :death
        = f.check_box :death_preventable
        = f.label :death_preventable
      .row.column
        = f.check_box :wound_infection
        = f.label :wound_infection
        = f.check_box :anesthesia_related
        = f.label :anesthesia_related

  .row.column                                  
    = f.label :description
    = f.text_area :description, rows: 6, placeholder: 'Enter complication description', required: true
  
  .row
    .column.medium-6
      = f.label :error_type
      = f.select :error_type, Complication::ErrorTypes,
                              { prompt: 'Select error type'}, required: true
    .column.medium-6
      = f.label :error_grade
      = f.select :error_grade, Complication::ErrorGradesWithSuffix,
                               { prompt: 'Select error grade'}, required: true

  .row.column
    = image_tag 'complication_error_grades.png'
  .field
  .actions
    = f.submit 'Save'

app/views/complications/edit.html.haml
.row.column
  %h1 Editing complication

= render 'form'

app/views/complications/index.html.haml
.row.column.expanded
  .table-scroll
    %table.hover
      %thead
        %tr
          %th Operation record
          %th Description
          %th Wound infection
          %th Death
          %th Preventable
          %th Death preventable
          %th Anesthesia related
          %th Error type
          %th Error grade
          %th
    
      %tbody
        - @complications.each do |complication|
          %tr
            %td= complication.operation_record
            %td= complication.description
            %td= complication.wound_infection
            %td= complication.death
            %td= complication.preventable
            %td= complication.death_preventable
            %td= complication.anesthesia_related
            %td= complication.error_type
            %td= complication.error_grade
            %td= index_links(complication)

.row.column.expanded
  = link_to 'New Complication', new_complication_path, class: 'button'

app/views/complications/new.html.haml
.row.column
  %h1 New complication

= render 'form'

app/views/complications/show.html.haml
.row.column
  %p#notice= notice

  %p
    %b Operation record:
    = @complication.operation_record
  %p
    %b Description:
    = @complication.description
  %p
    %b Wound infection:
    = @complication.wound_infection
  %p
    %b Death:
    = @complication.death
  %p
    %b Preventable:
    = @complication.preventable
  %p
    %b Death preventable:
    = @complication.death_preventable
  %p
    %b Anesthesia related:
    = @complication.anesthesia_related
  %p
    %b Error type:
    = @complication.error_type
  %p
    %b Error grade:
    = @complication.error_grade
  
  = link_to 'Edit', edit_complication_path(@complication)
  \|
  = link_to 'Back', complications_path