config/routes.rb
Rails.application.routes.draw do
  resources :complications
  resources :operation_records
  resources :doctors
  resources :patients

  root 'operation_records#index'

end

app/models/doctor.rb
# == Schema Information
#
# Table name: doctors
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  firm       :integer
#  role       :string
#  resident   :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Doctor < ActiveRecord::Base
  
  Firms = [1, 2]
  Roles = OpenStruct.new surgeon: 'Surgeon', 
                         anesthesiologist: 'Anesthesiologist', 
                         anesthesia_technician: 'Anesthesia Technician'
  
  validates :first_name, :last_name, :firm, 
            :role, presence: true
  validates :firm, inclusion: { in: Firms }
  validates :role, inclusion: { in: Roles.to_h.values }
  validates :resident, inclusion: { in: [true, false] }
  
  has_many :operation_records
  
  scope :surgeons, -> { where(role: Roles.surgeon) }
  scope :anesthesiologists, -> { where(role: [Roles.anesthesiologist, Roles.anesthesia_technician]) }
  
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:first_name, :last_name, :firm, :role, :resident)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.haml
= form_for @doctor do |f|
  - if @doctor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@doctor.errors.count, "error")} prohibited this doctor from being saved:"
      %ul
        - @doctor.errors.full_messages.each do |msg|
          %li= msg

  .row
    .column.medium-6
      = f.label :first_name
      = f.text_field :first_name, required: true
    .column.medium-6
      = f.label :last_name
      = f.text_field :last_name, required: true
  .row
    .column.medium-4
      = f.label :firm
      = f.select :firm, Doctor::Firms, { include_blank: true }, required: true
    .column.medium-4
      = f.label :role
      = f.select :role, Doctor::Roles.to_h.values, { include_blank: true }, required: true
    .column.medium-4
      = f.label :resident
      = f.select :resident, [['True', true], ['False', false]], { include_blank: true }, required: true
  .row.column
    .actions
      = f.submit 'Save', class: 'button'

app/views/doctors/edit.html.haml
.row.column
  %h1 Editing doctor

= render 'form'

app/views/doctors/index.html.haml
.row.column
  .table-scroll
    %table.hover
      %thead
        %tr
          %th First name
          %th Last name
          %th Firm
          %th Role
          %th Resident
          %th
    
      %tbody
        - @doctors.each do |doctor|
          %tr
            %td= doctor.first_name
            %td= doctor.last_name
            %td= doctor.firm
            %td= doctor.role
            %td= doctor.resident
            %td= index_links(doctor)

.row.column
  = link_to 'New Doctor', new_doctor_path, class: 'button'

app/views/doctors/new.html.haml
.row.column
  %h1 New doctor

= render 'form'

app/views/doctors/show.html.haml
.row.column
  %p#notice= notice
  
  %p
    %b First name:
    = @doctor.first_name
  %p
    %b Last name:
    = @doctor.last_name
  %p
    %b Firm:
    = @doctor.firm
  %p
    %b Role:
    = @doctor.role
  %p
    %b Resident:
    = @doctor.resident
  
  = link_to 'Edit', edit_doctor_path(@doctor)
  \|
  = link_to 'Back', doctors_path