config/routes.rb
Rails.application.routes.draw do
  resources :complications
  resources :operation_records
  resources :doctors
  resources :patients

  root 'operation_records#index'

end

app/models/operation_record.rb
# == Schema Information
#
# Table name: operation_records
#
#  id                  :integer          not null, primary key
#  patient_id          :integer
#  primary_surgeon_id  :integer
#  anesthesiologist_id :integer
#  operation_date      :date
#  pre_op_diagnosis    :string           is an Array
#  post_op_diagnosis   :string           is an Array
#  procedures          :string           is an Array
#  case_type           :string
#  reoperation         :boolean
#  duration            :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
# Indexes
#
#  index_operation_records_on_anesthesiologist_id  (anesthesiologist_id)
#  index_operation_records_on_patient_id           (patient_id)
#  index_operation_records_on_primary_surgeon_id   (primary_surgeon_id)
#

class OperationRecord < ActiveRecord::Base
  
  CaseTypes = %w(Emergency Elective)
  
  belongs_to :patient
  belongs_to :primary_surgeon, class_name: 'Doctor'
  belongs_to :anesthesiologist, class_name: 'Doctor'
  has_many :complications
  has_and_belongs_to_many :additional_surgeons, class_name: 'Doctor', join_table: 'operation_records_additional_surgeons'
  
  accepts_nested_attributes_for :patient
  accepts_nested_attributes_for :complications, allow_destroy: true
  
  validates :patient, :primary_surgeon, :anesthesiologist, 
            :operation_date, :pre_op_diagnosis, :post_op_diagnosis,
            :case_type, :duration,
            presence: true
  validates :case_type, inclusion: { in: CaseTypes }
  
  after_initialize :init_patient
  before_validation :clean_array_attrs
  
  scope :order_by_date, -> { order('operation_date DESC') }
  
  def self.op_durations
    (900...58500).step(900).to_a.map { |d| [Time.at(d).utc.to_s(:time), d] }
  end
  
  def self.existing_procedures
    pluck(:procedures).flatten.compact.uniq
  end
  
  def self.existing_diagnoses
    pluck(:pre_op_diagnosis, :post_op_diagnosis).flatten.compact.uniq
  end
  
  def duration_in_hours_minutes
    Time.at(duration).utc.to_s(:time)
  end
  
  def short_desc
    "#{operation_date} | Patient: #{patient.reg_no} | Primary surgeon: #{primary_surgeon.full_name}"
  end
  
  
private
  
  def init_patient
    patient ||= Patient.new
  end
    
  def clean_array_attrs
    [:procedures, :pre_op_diagnosis, :post_op_diagnosis].each do |array_attr|
      send(array_attr).reject!(&:blank?) if send(array_attr)
    end
  end
end

app/controllers/operation_records_controller.rb
class OperationRecordsController < ApplicationController
  before_action :set_operation_record, only: [:show, :edit, :update, :destroy]

  # GET /operation_records
  # GET /operation_records.json
  def index
    @operation_records = OperationRecord.order_by_date
  end

  # GET /operation_records/1
  # GET /operation_records/1.json
  def show
  end

  # GET /operation_records/new
  def new
    @operation_record = OperationRecord.new
  end

  # GET /operation_records/1/edit
  def edit
  end

  # POST /operation_records
  # POST /operation_records.json
  def create
    @operation_record = OperationRecord.new(operation_record_params)

    respond_to do |format|
      if @operation_record.save
        format.html { redirect_to @operation_record, notice: 'Operation record was successfully created.' }
        format.json { render :show, status: :created, location: @operation_record }
      else
        format.html { render :new }
        format.json { render json: @operation_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operation_records/1
  # PATCH/PUT /operation_records/1.json
  def update
    respond_to do |format|
      if @operation_record.update(operation_record_params)
        format.html { redirect_to @operation_record, notice: 'Operation record was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation_record }
      else
        format.html { render :edit }
        format.json { render json: @operation_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operation_records/1
  # DELETE /operation_records/1.json
  def destroy
    @operation_record.destroy
    respond_to do |format|
      format.html { redirect_to operation_records_url, notice: 'Operation record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation_record
      @operation_record = OperationRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_record_params
      params.require(:operation_record)
          .permit(
              :operation_date, :patient_id, :primary_surgeon_id, 
              :anesthesiologist_id, :case_type, :reoperation, :duration,
              patient_attributes: 
                  [:reg_no, :birth_year, :gender],
              complications_attributes: 
                  [
                      :id, :_destroy, :preventable, :death, 
                      :death_preventable, :wound_infection, 
                      :anesthesia_related, :description, 
                      :error_grade, error_type: []
                  ],
              additional_surgeon_ids: [], 
              procedures: [], 
              pre_op_diagnosis: [], 
              post_op_diagnosis: [],
          )
    end
end

app/helpers/operation_records_helper.rb
module OperationRecordsHelper
end

app/views/operation_records/_complication_fields.html.haml
.nested-fields
  .row.column.mtm
    .callout
      .row.column 
        %h3= f.object.new_record? ? 'New Complication' : "Complication #{f.index + 1}"
      .row.column
        %fieldset.fieldset
          %legend Complication issues
          .row.column
            = f.check_box :preventable
            = f.label :preventable
            = f.check_box :death
            = f.label :death
            = f.check_box :death_preventable
            = f.label :death_preventable
          .row.column
            = f.check_box :wound_infection
            = f.label :wound_infection
            = f.check_box :anesthesia_related
            = f.label :anesthesia_related
    
      .row.column
        = f.label :description
        = f.text_area :description, rows: 6, placeholder: 'Enter complication description', required: true
    
      .row
        .column.medium-6
          = f.label :error_type
          = f.select :error_type, Complication::ErrorTypes, {}, 
                                  required: true,
                                  multiple: true, 
                                  class: 'error-type-select'
        .column.medium-6
          = f.label :error_grade
          = f.select :error_grade, Complication::ErrorGradesWithSuffix,
                                   { prompt: 'Select error grade'}, required: true
          %p.help-text
            %a{ data: { open: 'complication-classification-modal' } }
              View Classification of Surgical Complications
            
      .row.column
        = link_to_remove_association "Remove Complication", f, class: 'button float-right', :data => { :confirm => 'Are you sure?' }

app/views/operation_records/_form.html.haml
= form_for @operation_record do |f|
  - if @operation_record.errors.any?
    #error_explanation
      %h2= "#{pluralize(@operation_record.errors.count, "error")} prohibited this operation_record from being saved:"
      %ul
        - @operation_record.errors.full_messages.each do |msg|
          %li= msg

  .row
    .column.medium-6
      .date-select
        = f.label :operation_date
        = f.date_select :operation_date, { start_year: DateTime.now.year, end_year: DateTime.now.year - 50,
                                         order: [:month, :day, :year], prompt: true }, required: true
    .column.medium-6
      #patient-wrap.input-group
        #patient-select
          = f.label :patient_id
          = f.select :patient_id, Patient.all.collect { |p| [p.reg_no, p.id] }, 
                                  { prompt: 'Select patient reg number' }, required: true, class: 'input-group-field'
        .input-group-button.v-align-bottom.nowrap
          = link_to_add_association 'Add new patient', f, :patient, class: 'button'
  
  .row
    .column.medium-6
      = f.label :primary_surgeon_id
      = f.select :primary_surgeon_id, Doctor.surgeons.collect { |d| [d.full_name, d.id] }, 
                                      { prompt: 'Select primary surgeon' }, required: true
    .column.medium-6
      = f.label :anesthesiologist_id
      = f.select :anesthesiologist_id, Doctor.anesthesiologists.collect { |d| [d.full_name, d.id] }, 
                                       { prompt: 'Select anesthesiologist' }, required: true
    
  .row.mbs
    .column.medium-6.mbs
      = f.label :additional_surgeon_ids, 'Additional Surgeons'
      = f.select :additional_surgeon_ids, Doctor.all.collect { |d| [d.full_name, d.id] }, {}, 
                                           multiple: true
    .column.medium-6
      = f.label :procedures
      = f.select :procedures, OperationRecord.existing_procedures, {}, 
                              multiple: true

  .row
    .column.medium-4
      = f.label :case_type
      = f.select :case_type, OperationRecord::CaseTypes, { prompt: 'Select case type' }, 
                             required: true
    .column.medium-4
      = f.label :reoperation
      = f.select :reoperation, [['True', true], ['False', false]], { prompt: 'Select...' }, required: true
    .column.medium-4
      = f.label :duration
      = f.select :duration, OperationRecord.op_durations, { prompt: 'Select duration' }, required: true
  
  .row.mbs
    .column.medium-6
      = f.label :pre_op_diagnosis
      = f.select :pre_op_diagnosis, OperationRecord.existing_diagnoses, {}, 
                                    multiple: true
    .column.medium-6
      = f.label :post_op_diagnosis
      = f.select :post_op_diagnosis, OperationRecord.existing_diagnoses, {}, 
                                     multiple: true
                                     
  .row.column.mtl
    %h4 Complications
    .divider
                                       
  #complications.row.column
    = f.fields_for :complications do |complication|
      = render 'complication_fields', f: complication
    .links
      = link_to_add_association 'Add New Complication', f, :complications, class: 'button warning float-right'

  .row.column
    .divider
    .actions
      = f.submit 'Save Operation Record', class: 'button'

-# Classification of surgical complications modal
#complication-classification-modal.reveal.large{ data: { reveal: true} }
  %button.close-button{ data: { close: true } }
    %span &times;
  = image_tag 'complication_error_grades.png'

:coffeescript
  ready = ->
    $('#operation_record_additional_surgeon_ids').select2()
    $('#operation_record_procedures').select2 tags: true
    $('#operation_record_pre_op_diagnosis').select2 tags: true
    $('#operation_record_post_op_diagnosis').select2 tags: true
  
    $('#patient-wrap').on 'cocoon:after-insert', ->
      $('#patient-select select').removeAttr('required')
      $('#patient-select').hide()
      $('#patient-wrap a.add_fields').hide()
      
    $('#patient-wrap').on 'cocoon:after-remove', ->
      $('#patient-select select').attr('required', true)
      $('#patient-select').show()
      $('#patient-wrap a.add_fields').show()
  
    
    $('#complications .error-type-select').each (index, element) ->
      $(element).select2()
    $('#complications').on 'cocoon:after-insert', (e, addedComplication) ->
      addedComplication.find('.error-type-select').select2()
  $(document).ready ready
  $(document).on 'page:load', ready

  

app/views/operation_records/_patient_fields.html.haml
.nested-fields
  .row
    .column.medium-4
      = f.label :reg_no
      = f.text_field :reg_no, required: true
    .column.medium-4
      = f.label :birth_year
      = f.select :birth_year, (1900..Date.today.year).to_a.reverse, { include_blank: true }, required: true
    .column.medium-4
      = f.label :gender
      = f.select :gender, Patient::Genders, { include_blank: true }, required: true
  
  .row.column
    = link_to_remove_association "Select existing patient", f, class: 'button small float-right'

app/views/operation_records/edit.html.haml
.row.column
  %h3= "Operation Record #{@operation_record.id}"
  .divider
= render 'form'

app/views/operation_records/index.html.haml
.row.column.expanded
  .table-scroll
    %table.hover
      %thead
        %tr
          %th Date
          %th Patient Reg #
          %th Patient Birth Year
          %th Patient Gender
          %th Primary surgeon
          %th Anesthesiologist
          %th Additional surgeons
          %th Procedures
          %th Case type
          %th Reoperation
          %th Duration
          %th Pre Op Diagnosis
          %th Pre Op Diagnosis
          %th
    
      %tbody
        - @operation_records.each do |operation_record|
          %tr
            %td{ style: 'white-space:nowrap' }= operation_record.operation_date
            %td= operation_record.patient.reg_no
            %td= operation_record.patient.birth_year
            %td= operation_record.patient.gender
            %td= operation_record.primary_surgeon.full_name
            %td= operation_record.anesthesiologist.full_name
            %td.pre-line= operation_record.additional_surgeons.map(&:full_name).join("<br/>").html_safe
            %td.pre-line= operation_record.procedures.join("<br/>").html_safe
            %td= operation_record.case_type
            %td= operation_record.reoperation
            %td= operation_record.duration_in_hours_minutes
            %td= operation_record.pre_op_diagnosis.join("<br/>").html_safe
            %td= operation_record.post_op_diagnosis.join("<br/>").html_safe
            %td= index_links(operation_record)

.row.column.expanded
  = link_to 'New Operation record', new_operation_record_path, class: 'button'

app/views/operation_records/new.html.haml
.row.column
  %h1 New Operation Record

= render 'form'

app/views/operation_records/show.html.haml
.row.column
  %p#notice= notice
  
  %p
    %b Operation date:
    = @operation_record.operation_date
  %p
    %b Patient:
    = @operation_record.patient.reg_no
  %p
    %b Primary surgeon:
    = @operation_record.primary_surgeon.full_name
  %p
    %b Anesthesiologist:
    = @operation_record.anesthesiologist.full_name
  %p
    %b Additional surgeons:
    = @operation_record.additional_surgeons.map &:full_name
  %p
    %b Procedures:
    = @operation_record.procedures
  %p
    %b Case type:
    = @operation_record.case_type
  %p
    %b Reoperation:
    = @operation_record.reoperation
  %p
    %b Duration:
    = @operation_record.duration_in_hours_minutes
  %p
    %b Pre op diagnosis:
    = @operation_record.pre_op_diagnosis
  %p
    %b Post op diagnosis:
    = @operation_record.post_op_diagnosis
  %p
    %b Complications:
    = @operation_record.complications.map &:id
  
  = link_to 'Edit', edit_operation_record_path(@operation_record)
  \|
  = link_to 'Back', operation_records_path