config/routes.rb
Rails.application.routes.draw do
  resources :complications
  resources :operation_records
  resources :doctors
  resources :patients

  root 'operation_records#index'

end

app/views/layouts/_navigation.html.haml
#leftMenu.off-canvas.position-left.reveal-for-large{ 'data-off-canvas' => true }

  %ul.vertical.menu
    %li
      = link_to root_path do
        %i.fi-page-multiple
        %span Operation Records
    
    %li
      = link_to doctors_path do
        %i.fi-torsos
        %span Doctors

    %li
      = link_to patients_path do
        %i.fi-torsos-all
        %span Patients
    
    -#%li
    -#  = link_to complications_path do
    -#    %i.fi-alert
    -#    %span Complications

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= page_title

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"
    = csrf_meta_tags

  %body
    .off-canvas-wrapper
      .off-canvas-wrapper-inner{ 'data-off-canvas-wrapper' => true }
        = render 'layouts/navigation'        
        
        .off-canvas-content{ 'data-off-canvas-content' => true }
          .title-flash-wrapper
            .title-bar
              .title-bar-left
                %button.menu-icon.hide-for-large{"data-open" => "leftMenu", :type => "button"}
                %span.title-bar-title= page_title
            - flash.each do |key, value|
              .flash{ class: key }
                = value
              
          = yield